/** Fixture for /m.html?demo=1, realistic paletas menu preview */
export const DEMO_MENU = {
  slug: 'demo',
  published: true,
  businessName: 'Paletas de Sofía',
  tagline: 'Artesanales · Pedidos por WhatsApp',
  whatsapp: '5215512345678',
  phone: '5512345678',
  coverImage: '',
  logoImage: '',
  note: 'Pedidos con 1 día de anticipación. Entrega en zona centro. Mínimo 6 paletas.',
  categories: [
    { id: 'cat_frutales', name: 'Frutales' },
    { id: 'cat_cremosas', name: 'Cremosas' },
    { id: 'cat_especiales', name: 'Especiales' },
  ],
  items: [
    {
      id: 'd1',
      name: 'Fresa natural',
      price: '25',
      description: 'Con trozos de fresa fresca',
      categoryId: 'cat_frutales',
      image: '',
      available: true,
    },
    {
      id: 'd2',
      name: 'Mango chile',
      price: '28',
      description: 'Mango maduro con toque de chile',
      categoryId: 'cat_frutales',
      image: '',
      available: true,
    },
    {
      id: 'd3',
      name: 'Limón',
      price: '22',
      description: 'Ácida y refrescante',
      categoryId: 'cat_frutales',
      image: '',
      available: true,
    },
    {
      id: 'd4',
      name: 'Chocolate belga',
      price: '32',
      description: 'Cacao intenso, cremosa',
      categoryId: 'cat_cremosas',
      image: '',
      available: true,
    },
    {
      id: 'd5',
      name: 'Vainilla',
      price: '28',
      description: 'Clásica y suave',
      categoryId: 'cat_cremosas',
      image: '',
      available: true,
    },
    {
      id: 'd6',
      name: 'Coco',
      price: '30',
      description: 'Leche de coco natural',
      categoryId: 'cat_cremosas',
      image: '',
      available: false,
    },
    {
      id: 'd7',
      name: 'Oreo rellena',
      price: '38',
      description: 'Centro de galleta triturada',
      categoryId: 'cat_especiales',
      image: '',
      available: true,
    },
    {
      id: 'd8',
      name: 'Nutella',
      price: '40',
      description: 'Rellena de avellana',
      categoryId: 'cat_especiales',
      image: '',
      available: true,
    },
    {
      id: 'd9',
      name: 'Combo 6 mixtas',
      price: '150',
      description: 'Elige 6 sabores · ahorro vs unitario',
      categoryId: 'cat_especiales',
      image: '',
      available: true,
    },
  ],
};
